# -*- coding: utf-8 -*-
"""table extraction csv file from website.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHIzqsYbSy7wieiAMe0vp-22gioEbG33
"""

import pandas  as pd

premeir21 =pd.read_csv('https://football-data.co.uk/mmz4281/2324/E0.csv')

premeir21.rename(columns={'FTHG':'home goals','FTAG':'away goals'},inplace=True )