# -*- coding: utf-8 -*-
"""table extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/173o8Gx0i4aY9ppwQYtO8BJkU-1ECkKRk
"""

!pip install pandas
import pandas as pd

simpsons = pd.read_html('https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes_(seasons_1%E2%80%9320)#Season_5_(1993%E2%80%9394)')

len(simpsons)

simpsons[1]